WIP on migrating to UV

diff --git a/docs/ros_start/Makefile b/docs/ros_start/Makefile
--- a/docs/ros_start/Makefile
+++ b/docs/ros_start/Makefile
@@ -1,5 +1,6 @@
 NAME := f1tenth
 POETRY := $(shell command -v poetry 2> /dev/null)
+UV := $(shell command -v uv 2> /dev/null)
 SHELL := /bin/zsh
 .DEFAULT_GOAL := help
 
@@ -9,7 +10,7 @@ help:
 		@echo "Please use 'make <target>' where <target> is one of"
 		@echo ""
 		@echo "  clean       remove all temporary files"
-		@echo "  activate    activates the poetry environment"
+		@echo "  activate    activates the uv environment"
 		@echo "  build       build the project with colcon"
 		@echo ""
 		@echo "Check the Makefile to know exactly what each target is doing."
@@ -18,41 +19,61 @@ help:
 clean:
 	rm -rf build/ install/ log/
 
-check-poetry:
-	@if [ $(shell which poetry | grep poetry | wc -l) -gt 0 ]; then \
-		echo "Poetry is installed."; \
+check-uv:
+	@if [ $(shell which uv | grep uv | wc -l) -gt 0 ]; then \
+		echo "UV is installed."; \
 	else \
-		echo "Poetry is not installed. Please install it."; \
+		echo "UV is not installed. Please install it."; \
 		exit 1; \
 	fi
 
 
-check-env: check-poetry
-	@poetry env info --path > /dev/null 2>&1 || { echo "Poetry environment is not activated, \
-	run 'make activate' first, then go back two directories"; exit 1; } \
+# check-env: check-uv
+# 	@uv env info --path > /dev/null 2>&1 || { echo "UV environment is not activated, \
+# 	run 'make activate' first, then go back two directories"; exit 1; } \
 
 
-activate: check-poetry
-	@if poetry env info --path > /dev/null 2>&1; then \
-		echo "Poetry environment is activated."; \
-	else \
-	    echo "Poetry environment is not activated. Activating..."; \
-		cd src/f1tenth_system; \
-		poetry shell || { echo "Failed to activate Poetry environment."; exit 1; } \
-	fi
+# activate: check-uv
+# 	@if uv env info --path > /dev/null 2>&1; then \
+# 		echo "UV environment is activated."; \
+# 	else \
+# 	    echo "UV environment is not activated. Activating..."; \
+# 		cd src/f1tenth_system; \
+# 		source .venv/bin/activate || { echo "Failed to activate UV environment."; exit 1; } \
+# 	fi
 
-build: check-env
-	python -m colcon build --symlink-install
-	source install/setup.zsh
+.PHONY: build
+build:
+	cd src/f1tenth_system; \
+	source .venv/bin/activate || { echo "Failed to activate UV environment."; exit 1; }; \
+	cd ../..; \
+	python -m colcon build --symlink-install; \
+	source install/setup.zsh \
 
-run_manual: check-env
+.PHONY: run_manual
+run_manual:
+	cd src/f1tenth_system; \
+	source .venv/bin/activate || { echo "Failed to activate UV environment."; exit 1; }; \
+	cd ../..; \
 	ros2 launch f1tenth_stack bringup_base_launch.py
 
-run_straight: check-env
+.PHONY: run_straight
+run_straight:
+	cd src/f1tenth_system; \
+	source .venv/bin/activate || { echo "Failed to activate UV environment."; exit 1; }; \
+	cd ../..; \
 	ros2 launch f1tenth_stack bringup_auto_straight_launch.py
 
-run_roomba: check-env
+.PHONY: run_roomba
+run_roomba:
+	cd src/f1tenth_system; \
+	source .venv/bin/activate || { echo "Failed to activate UV environment."; exit 1; }; \
+	cd ../..; \
 	ros2 launch f1tenth_stack bringup_auto_roomba_launch.py
 
-run_wiggle: check-env
+.PHONY: run_wiggle
+run_wiggle:
+	cd src/f1tenth_system; \
+	source .venv/bin/activate || { echo "Failed to activate UV environment."; exit 1; }; \
+	cd ../..; \
 	ros2 launch f1tenth_stack bringup_auto_wiggle_launch.py
