Run formatting and update submodules

diff --git a/docs/ros_start/Makefile b/docs/ros_start/Makefile
--- a/docs/ros_start/Makefile
+++ b/docs/ros_start/Makefile
@@ -14,29 +14,39 @@ help:
 		@echo ""
 		@echo "Check the Makefile to know exactly what each target is doing."
 
-
 .PHONY: clean
 clean:
 	rm -rf build/ install/ log/
 
+check-poetry:
+	@if [ $(shell which poetry | grep poetry | wc -l) -gt 0 ]; then \
+		echo "Poetry is installed."; \
+	else \
+		echo "Poetry is not installed. Please install it."; \
+		exit 1; \
+	fi
 
-.PHONY: activate
-activate:
-	# NOTE: assumes you are at the top level of the ROS project
-	cd src/f1tenth_system && poetry shell
+
+check-env: check-poetry
+	@poetry env info --path > /dev/null 2>&1 || { echo "Poetry environment is not activated, \
+	run 'make activate' first, then go back two directories"; exit 1; } \
 
 
-.PHONY: build
-build:
+activate: check-poetry
+	@if poetry env info --path > /dev/null 2>&1; then \
+		echo "Poetry environment is activated."; \
+	else \
+	    echo "Poetry environment is not activated. Activating..."; \
+		cd src/f1tenth_system; \
+		poetry shell || { echo "Failed to activate Poetry environment."; exit 1; } \
+	fi
+
+build: check-env
 	python -m colcon build --symlink-install
 	source install/setup.zsh
 
-
-.PHONY: run_manual
-run_manual:
+run_manual: check-env
 	ros2 launch f1tenth_stack bringup_base_launch.py
 
-
-.PHONY: run_wiggle
-run_wiggle:
+run_wiggle: check-env
 	ros2 launch f1tenth_stack bringup_auto_wiggle_launch.py
